import type { ObjectSlotPosition, RoomObject } from "../types/object";

const IMPORTED_OBJECT_DESCRIPTION = "Imported from the objects folder.";

const withDefaultImageScale = (objects: RoomObject[]) => objects.map((object) => ({ imageScale: 2.0, ...object }));

export const ROOM_OBJECTS: RoomObject[] = withDefaultImageScale([
  {
    objectKey: "carpet",
    name: "Carpet",
    slotKey: "carpet",
    imageUrl: "/objects/object-01.png",
    imageScale: 4.0,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "poster",
    name: "Poster",
    slotKey: "poster",
    imageUrl: "/objects/object-02.png",
    imageScale: 2.5,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "letter",
    name: "Letter",
    slotKey: "letter",
    imageUrl: "/objects/object-03.png",
    imageScale: 1,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "mug",
    name: "Mug",
    slotKey: "mug",
    imageUrl: "/objects/object-04.png",
    imageScale: 0.7,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "plant",
    name: "Plant",
    slotKey: "plant",
    imageUrl: "/objects/object-05.png",
    imageScale: 1.5,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "radio",
    name: "Radio",
    slotKey: "radio",
    imageUrl: "/objects/object-06.png",
    imageScale: 1.7,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "curtain",
    name: "Curtain",
    slotKey: "curtain",
    imageUrl: "/objects/object-07.png",
    imageScale: 4.8,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "shoes",
    name: "Shoes",
    slotKey: "shoes",
    imageUrl: "/objects/object-08.png",
    imageScale: 1.3,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "frame",
    name: "Frame",
    slotKey: "frame",
    imageUrl: "/objects/object-09.png",
    imageScale: 1.6,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "bed",
    name: "Bed",
    slotKey: "bed",
    imageUrl: "/objects/object-10.png",
    imageScale: 4.5,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "umbrella",
    name: "Umbrella",
    slotKey: "umbrella",
    imageUrl: "/objects/object-11.png",
    imageScale: 1.7,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "book",
    name: "Book",
    slotKey: "book",
    imageUrl: "/objects/object-12.png",
    imageScale: 1.0,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "desk",
    name: "책상",
    slotKey: "desk",
    imageUrl: "/objects/object-13.png",
    imageScale: 3.2,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "cat",
    name: "고양이",
    slotKey: "cat",
    imageUrl: "/objects/object-14.png",
    imageScale: 1.5,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "candle",
    name: "양초",
    slotKey: "candle",
    imageUrl: "/objects/object-15.png",
    imageScale: 0.8,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "rug",
    name: "러그",
    slotKey: "rug",
    imageUrl: "/objects/object-16.png",
    imageScale: 3.6,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "clock",
    name: "시계",
    slotKey: "clock",
    imageUrl: "/objects/object-17.png",
    imageScale: 1.2,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "stand_lamp",
    name: "스탠드조명",
    slotKey: "stand_lamp",
    imageUrl: "/objects/object-18.png",
    imageScale: 2.4,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
  {
    objectKey: "bookshelf",
    name: "책장",
    slotKey: "bookshelf",
    imageUrl: "/objects/object-19.png",
    imageScale: 3.8,
    description: IMPORTED_OBJECT_DESCRIPTION,
    allowPrivate: true,
    allowPlaza: true,
  },
]);

const LEGACY_OBJECT_KEY_MAP: Record<string, string> = {
  wooden_chair: "carpet",
  old_radio: "radio",
  small_plant: "plant",
  mug_cup: "mug",
  doll: "bed",
  tiny_cloud: "curtain",
  pencil: "book",
};

export const OBJECT_BY_KEY = ROOM_OBJECTS.reduce<Record<string, RoomObject>>((acc, object) => {
  acc[object.objectKey] = object;
  return acc;
}, {});

Object.entries(LEGACY_OBJECT_KEY_MAP).forEach(([legacyKey, objectKey]) => {
  const object = OBJECT_BY_KEY[objectKey];

  if (object && !OBJECT_BY_KEY[legacyKey]) {
    OBJECT_BY_KEY[legacyKey] = object;
  }
});

export const ROOM_SLOT_POSITIONS: Record<string, ObjectSlotPosition> = {
  carpet: { x: 40, y: 84, offsetX: 8, offsetY: 0 },
  poster: { x: 60, y: 30, offsetX: 9, offsetY: 2 },
  letter: { x: 74, y: 66, offsetX: 7, offsetY: -2, zIndex: 20 },
  mug: { x: 60, y: 60, offsetX: -8, offsetY: 2 },
  plant: { x: 39, y: 78, offsetX: 9, offsetY: 0 },
  radio: { x: 78, y: 30, offsetX: -8, offsetY: 2 },
  curtain: { x: 22, y: 30, offsetX: 0, offsetY: -4 },
  shoes: { x: 30, y: 88, offsetX: 8, offsetY: 0 },
  frame: { x: 82, y: 26, offsetX: -10, offsetY: 2 },
  bed: { x: 75, y: 68, offsetX: 7, offsetY: -3, zIndex: 10 },
  umbrella: { x: 10, y: 75, offsetX: 8, offsetY: 0 },
  book: { x: 63, y: 65, offsetX: 7, offsetY: -3 },
  desk: { x: 76, y: 72, offsetX: -7, offsetY: 2, zIndex: 8 },
  cat: { x: 57, y: 63, offsetX: 6, offsetY: -2, zIndex: 22 },
  candle: { x: 45, y: 49, offsetX: 6, offsetY: 0, zIndex: 24 },
  rug: { x: 51, y: 86, offsetX: 8, offsetY: 0, zIndex: 4 },
  clock: { x: 85, y: 34, offsetX: -6, offsetY: 0, zIndex: 20 },
  stand_lamp: { x: 14, y: 62, offsetX: 6, offsetY: 2, zIndex: 18 },
  bookshelf: { x: 50, y: 46, offsetX: 6, offsetY: 0, zIndex: 6 },
};

export const PLAZA_SLOT_POSITIONS: Record<string, ObjectSlotPosition> = {
  carpet: { x: 42, y: 80, offsetX: 10, offsetY: 0 },
  poster: { x: 52, y: 28, offsetX: 10, offsetY: 0 },
  letter: { x: 56, y: 63, offsetX: 10, offsetY: 0, zIndex: 20 },
  mug: { x: 74, y: 57, offsetX: -9, offsetY: 5 },
  plant: { x: 36, y: 76, offsetX: 11, offsetY: 0 },
  radio: { x: 76, y: 61, offsetX: -9, offsetY: 5 },
  curtain: { x: 18, y: 44, offsetX: 7, offsetY: 8 },
  shoes: { x: 35, y: 82, offsetX: 11, offsetY: 0 },
  frame: { x: 64, y: 29, offsetX: 10, offsetY: 0 },
  bed: { x: 56, y: 67, offsetX: 9, offsetY: -5, zIndex: 10 },
  umbrella: { x: 13, y: 72, offsetX: 8, offsetY: 2 },
  book: { x: 64, y: 67, offsetX: 9, offsetY: -5 },
  desk: { x: 74, y: 66, offsetX: -9, offsetY: 5, zIndex: 8 },
  cat: { x: 48, y: 72, offsetX: 9, offsetY: -4, zIndex: 22 },
  candle: { x: 58, y: 54, offsetX: 9, offsetY: -4, zIndex: 22 },
  rug: { x: 45, y: 82, offsetX: 10, offsetY: 0, zIndex: 4 },
  clock: { x: 68, y: 30, offsetX: 10, offsetY: 0, zIndex: 18 },
  stand_lamp: { x: 19, y: 58, offsetX: 8, offsetY: 2, zIndex: 18 },
  bookshelf: { x: 43, y: 55, offsetX: 9, offsetY: -4, zIndex: 8 },
};
